apiVersion: v1
kind: ConfigMap
metadata:
  name: trial-templates
  namespace: kubeflow-user-example-com
  labels:
    katib.kubeflow.org/component: trial-templates  # must be 'trial-templates'
data:
  mxnetMnistTemplate.yaml: |-
    apiVersion: batch/v1
      kind: Job
      spec:
        template:
          metadata:
              annotations:
                sidecar.istio.io/inject: "false"
          spec:
            containers:
              - name: training-container
                image: docker.io/kubeflowkatib/mxnet-mnist:latest
                command:
                  - "python3"
                  - "/opt/mxnet-mnist/mnist.py"
                  - "--batch-size=64"
                  - "--lr=${trialParameters.learningRate}"
                  - "--num-layers=${trialParameters.numberLayers}"
                  - "--optimizer=${trialParameters.optimizer}"
            restartPolicy: Never
  pyTorchMnistFileLogs.yaml: |-
    apiVersion: batch/v1
    kind: Job
    spec:
      template:
        metadata:
            annotations:
              sidecar.istio.io/inject: "false"
        spec:
          containers:
            - name: training-container
              image: docker.io/kubeflowkatib/pytorch-mnist:latest
              command:  
                - "python3"
                - "/opt/pytorch-mnist/mnist.py"
                - "--epochs=2"
                - "--lr=${trialParameters.learningRate}"
                - "--momentum=${trialParameters.momentum}"
          restartPolicy: Never
  # - "--log-path=/katib/mnist.log"

  # For ConfigMap templates double quotes must set in commands to correct parse JSON parameters in Trial Template (e.g nn_config, architecture)
  enasCPUTemplate.yaml: |-
    apiVersion: batch/v1
    kind: Job
    spec:
      template:
        metadata:
              annotations:
                sidecar.istio.io/inject: "false"
        spec:
          containers:
            - name: training-container
              image: docker.io/kubeflowkatib/enas-cnn-cifar10-cpu:latest
              command:
                - python3
                - -u
                - RunTrial.py
                - --num_epochs=1
                - "--architecture=\"${trialParameters.neuralNetworkArchitecture}\""
                - "--nn_config=\"${trialParameters.neuralNetworkConfig}\""
          restartPolicy: Never
  TFJobTemplate.yaml: |-
    apiVersion: kubeflow.org/v1
    kind: TFJob
    spec:
      tfReplicaSpecs:                      
        Worker:
          replicas: 2
          restartPolicy: OnFailure
          template:
            metadata:
              annotations:
                sidecar.istio.io/inject: "false"
            spec:
              containers:
                - name: tensorflow
                  image: docker.io/kubeflowkatib/tf-mnist-with-summaries:latest
                  command:
                    - "python"
                    - "/opt/tf-mnist-with-summaries/mnist.py"
                    - "--epochs=1"
                    - "--learning-rate=${trialParameters.learningRate}"
                    - "--batch-size=${trialParameters.batchSize}"
                    - "--log-path=/mnist-with-summaries-logs" 
  pytorchJobTemplate.yaml: |-
    apiVersion: kubeflow.org/v1
    kind: PyTorchJob
    spec:
      pytorchReplicaSpecs:
        Master:
          replicas: 1
          restartPolicy: OnFailure
          template:
            metadata:
              annotations:
                sidecar.istio.io/inject: "false"
            spec:
              containers:
                - name: pytorch
                  image: docker.io/kubeflowkatib/pytorch-mnist:latest
                  imagePullPolicy: Always
                  command:
                    - "python3"
                    - "/opt/pytorch-mnist/mnist.py"
                    - "--epochs=1"
                    - "--lr=${trialParameters.learningRate}"
                    - "--momentum=${trialParameters.momentum}"
        Worker:
          replicas: 2
          restartPolicy: OnFailure
          template:
            metadata:
              annotations:
                sidecar.istio.io/inject: "false"
            spec:
              containers:
                - name: pytorch
                  image: docker.io/kubeflowkatib/pytorch-mnist:latest
                  imagePullPolicy: Always
                  command:
                    - "python3"
                    - "/opt/pytorch-mnist/mnist.py"
                    - "--epochs=1"
                    - "--lr=${trialParameters.learningRate}"
                    - "--momentum=${trialParameters.momentum}"
                    